title: Using Zotero for Citation Management
remote_theme: ubc-library-rc/rc-workshop-template
footer_content: "<a href=\"https://github.com/ubc-library-rc/refworks\">View workshop content in GitHub</a>"

theme: jekyll-theme-cayman